### ISSUE TITLE
Generate Visual Studio csproj files for csharp code.

### ISSUE THREAD

**Issue by zaphar** [bazelbuild/rules_dotnet#12] opened 2016-04-16 03:03 UTC
It would be nice if a csharp_binary or csharp_library target could be used to generate csprob files for the IDE users out there. It would go a long way to making this usable by MonoDevelop users.

**Comment by davidzchen** [comment] 2016-04-17 07:41
+cc @dslomov 

This would be an excellent use case for Skylark Aspects.

**Comment by lupin-de-mid** [comment] 2020-09-08 15:15
May be anybody has some hints how to generate this project file from bazel rules

**Comment by lupin-de-mid** [comment] 2020-09-08 15:45
I'm ready to generate this from csharp, but may be there are more bazelish way

**Comment by purkhusid** [comment] 2022-08-05 12:50
Duplicate of #258. Closing

**Closed by purkhusid** 2022-08-05 12:50 UTC
Labels: enhancement
