### ISSUE TITLE
Use csproj file to configure the basel rule

### ISSUE THREAD

**Issue by lehmamic** [bazelbuild/rules_dotnet#152] opened 2019-12-27 09:24 UTC
In the dot net world, the csproj files are required by most of the IDEs and Tools, e.g. Visual Studio or the DotNet CLI.

If I'm using those tools for development, I never can be sure that the Bazel Rule will generate the same as in my dev IDE, which makes it useless for me in Enterprise Projects.

I suggest you'll find a way to use the csproj to configure the rule or even better, make the rule really using the underlying toolset so we have to deference between Bazel builds and csproj builds.

**Comment by zaphar** [comment] 2020-01-11 03:58
This use case would probably be better handled by issue #12 instead. Generating a csproj from the bazel rule would be a better direction than the other way around.

**Comment by purkhusid** [comment] 2022-08-05 12:40
Duplicate of #258. Closing

**Closed by purkhusid** 2022-08-05 12:40 UTC
